services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.prod
    volumes:
      - ./data/assets:/app/assets
      - ./data/private_assets:/app/private_assets

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    volumes: []
